spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/{DB_Name}
    username: #{Id}
    password: #{Password}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create