server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: clientIdTest
            client-secret: clientSecretTest
          facebook:
            client-id: clientIdTest
            client-secret: clientSecretTest

kakao:
  client:
    # change clientId
    clientId: clientIdTest
    accessTokenUri: https://kauth.kakao.com/oauth/token
    userAuthorizationUri: https://kauth.kakao.com/oauth/authorize
  resource:
    userInfoUri: https://kapi.kakao.com/v1/user/me
---
spring:
  profiles: local
server:
  port: 8080
---
spring:
  profiles: dev
server:
  port: 8081
---
spring:
  profiles: real
server:
  port: 8082
---
property:
  test:
    name: property depth test
propertyTest: test
propertyTestList: a,b,c
fruit:
  list:
    - name: banana
      color: yellow
    - name: apple
      color: red
    - name: water melon
      color: green
season:
  season-name: spring
  season_month: april
  seasonFlower: blossom
  seasonweather: sunny
---
datasource:
  url: jdbc:h2:mem:testdb
spring:
  h2:
    console:
      enabled: true