spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/{DBName}
    username: {Id}
    password: {Password}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
  devtools:
    livereload:
      enabled: true
      port: 35730
server:
  port: 8081